comment everything out

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -100,27 +100,27 @@ bpwatch start pre_compile
 bpwatch stop pre_compile
 
 # Install libjpeg
-curl -A "Mozilla" --remote-name http://www.ijg.org/files/jpegsrc.v9a.tar.gz
-tar -xzvf jpegsrc.v9a.tar.gz
-if [ $? != 0 ]; then
-  puts-warn "libjpeg is not available for this stack ($STACK)."
-  puts-warn "Aborting."
-  exit 1
-fi
-cd jpeg-9a
-./configure --prefix=$BUILD_DIR/lib
-make
-make install
-if [ $? != 0 ]; then
-  puts-warn "libjpeg installation failed."
-  puts-warn "Aborting."
-  exit 1
-fi
-set-env LIBRARY_PATH '$BUILD_DIR/lib:$LIBRARY_PATH'
-set-env LD_LIBRARY_PATH '$BUILD_DIR/lib:$LD_LIBRARY_PATH'
+#curl -A "Mozilla" --remote-name http://www.ijg.org/files/jpegsrc.v9a.tar.gz
+#tar -xzvf jpegsrc.v9a.tar.gz
+#if [ $? != 0 ]; then
+#  puts-warn "libjpeg is not available for this stack ($STACK)."
+#  puts-warn "Aborting."
+#  exit 1
+#fi
+#cd jpeg-9a
+#./configure --prefix=$BUILD_DIR/lib
+#make
+#make install
+#if [ $? != 0 ]; then
+#  puts-warn "libjpeg installation failed."
+#  puts-warn "Aborting."
+#  exit 1
+#fi
+#set-env LIBRARY_PATH '$BUILD_DIR/lib:$LIBRARY_PATH'
+#set-env LD_LIBRARY_PATH '$BUILD_DIR/lib:$LD_LIBRARY_PATH'
 
 # Switch back to repo's context
-cd $BUILD_DIR
+#cd $BUILD_DIR
 
 # If no requirements given, assume `setup.py develop`.
 if [ ! -f requirements.txt ]; then
