modified compile file

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -16,6 +16,7 @@ ROOT_DIR=$(dirname $BIN_DIR)
 BUILD_DIR=$1
 CACHE_DIR=$2
 ENV_DIR=$3
+USER_DIR='user'
 
 
 CACHED_DIRS=".heroku"
@@ -87,40 +88,38 @@ export PYTHONUNBUFFERED=1
 export LANG=en_US.UTF-8
 export C_INCLUDE_PATH=/app/.heroku/vendor/include:$BUILD_DIR/.heroku/vendor/include:/app/.heroku/python/include
 export CPLUS_INCLUDE_PATH=/app/.heroku/vendor/include:$BUILD_DIR/.heroku/vendor/include:/app/.heroku/python/include
-export LIBRARY_PATH=/app/.heroku/vendor/lib:$BUILD_DIR/.heroku/vendor/lib:/app/.heroku/python/lib
-export LD_LIBRARY_PATH=/app/.heroku/vendor/lib:$BUILD_DIR/.heroku/vendor/lib:/app/.heroku/python/lib
+export LIBRARY_PATH=/app/.heroku/vendor/lib:$BUILD_DIR/.heroku/vendor/lib:/app/.heroku/python/lib:$USER_DIR/lib
+export LD_LIBRARY_PATH=/app/.heroku/vendor/lib:$BUILD_DIR/.heroku/vendor/lib:/app/.heroku/python/lib:$USER_DIR/lib
 export PKG_CONFIG_PATH=/app/.heroku/vendor/lib/pkg-config:$BUILD_DIR/.heroku/vendor/lib/pkg-config:/app/.heroku/python/lib/pkg-config
 
-# Switch to the repo's context.
-cd $BUILD_DIR
+# Switch to the user's context.
+mkdir -p $USER_DIR/lib
+cd $USER_DIR
+
+# Install libjpeg
+curl -A "Mozilla" --remote-name http://www.ijg.org/files/jpegsrc.v9a.tar.gz
+tar -xzvf jpegsrc.v9a.tar.gz
+if [ $? != 0 ]; then
+  puts-warn "libjpeg is not available for this stack ($STACK)."
+  puts-warn "Aborting."
+  exit 1
+fi
+cd jpeg-9a
+./configure --prefix=$USER_DIR/lib
+make
+make install
+if [ $? != 0 ]; then
+  puts-warn "libjpeg installation failed."
+  puts-warn "Aborting."
+  exit 1
+fi
 
 # Experimental pre_compile hook.
 bpwatch start pre_compile
   source $BIN_DIR/steps/hooks/pre_compile
 bpwatch stop pre_compile
 
-# Install libjpeg
-#curl -A "Mozilla" --remote-name http://www.ijg.org/files/jpegsrc.v9a.tar.gz
-#tar -xzvf jpegsrc.v9a.tar.gz
-#if [ $? != 0 ]; then
-#  puts-warn "libjpeg is not available for this stack ($STACK)."
-#  puts-warn "Aborting."
-#  exit 1
-#fi
-#cd jpeg-9a
-#./configure --prefix=$BUILD_DIR/lib
-#make
-#make install
-#if [ $? != 0 ]; then
-#  puts-warn "libjpeg installation failed."
-#  puts-warn "Aborting."
-#  exit 1
-#fi
-#set-env LIBRARY_PATH '$BUILD_DIR/lib:$LIBRARY_PATH'
-#set-env LD_LIBRARY_PATH '$BUILD_DIR/lib:$LD_LIBRARY_PATH'
 
-# Switch back to repo's context
-#cd $BUILD_DIR
 
 # If no requirements given, assume `setup.py develop`.
 if [ ! -f requirements.txt ]; then
