play with build-pack

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -99,6 +99,24 @@ bpwatch start pre_compile
   source $BIN_DIR/steps/hooks/pre_compile
 bpwatch stop pre_compile
 
+# Install libjpeg
+message 
+curl --remote-name http://www.ijg.org/files/jpegsrc.v9a.tar.gz | tar -xzvf
+if [ $? != 0 ]; then
+  puts-warn "libjpeg is not available for this stack ($STACK)."
+  puts-warn "Aborting."
+  exit 1
+fi
+cd jpeg-9a
+./configure
+make
+make install
+if [ $? != 0 ]; then
+  puts-warn "libjpeg installation failed."
+  puts-warn "Aborting."
+  exit 1
+fi
+
 # If no requirements given, assume `setup.py develop`.
 if [ ! -f requirements.txt ]; then
   echo "-e ." > requirements.txt
